#!/bin/sh

# Use neovim for vim if present.
[ -x "$(command -v nvim)" ] && alias vim="nvim" vimdiff="nvim -d"

# Use $XINITRC variable if file exists.
[ -f "$XINITRC" ] && alias startx="startx $XINITRC"

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

# Verbosity and settings that you pretty much just always are going to want.
alias \
	cp="cp -iv" \
	mv="mv -iv" \
	bc="bc -ql" \
	mkd="mkdir -pv" \
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ffmpeg="ffmpeg -hide_banner"

alias rm="trash -v" # aliased to trash-cli


# Colorize commands when possible.
alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto" \
	cmatrix='cmatrix -s -a -C blue'

# These common commands are just too long! Abbreviate them.
alias \
	ka="killall" \
	g="git" \
	trem="transmission-remote" \
	YT="youtube-viewer" \
	sdn="shutdown -h now" \
	e="$EDITOR" \
	v="$EDITOR" \
	p="pacman" \
	xi="sudo xbps-install" \
	xr="sudo xbps-remove -R" \
	xq="xbps-query" \
	z="zathura" \
	todo="$EDITOR $TODO"

# Edit config
alias \
	cfa="$EDITOR ~/.config/shell/aliases" \
	cfz="$EDITOR ~/.config/zsh/.zshrc" \
	cfv="$EDITOR ~/.config/nvim" \
	cft="$EDITOR ~/.config/tmux/tmux.conf" \

# Tmux Aliases
alias \
	tmls="tmux ls" \
	tmns="tmux new -s" \
	tmks="tmux kill-session -t"\
	tma="tmux a"\
	tmas="tmux attach -t"\
